### ISSUE TITLE
Use rapidjson python package.

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/python-rapidjson-feedstock#2]
It would probably make sense to use the rapidjson conda package rather than building from a submodule.

It seems that the setup.py of `python-rapidjson` makes a strong assumption on rapidjson coming from a submodule. I am opening an issue upstream to see if they can allow building with another rapidjson.

https://github.com/python-rapidjson/python-rapidjson/issues/60

**Comment by hajapy** [comment]
Looks like there is now support for this upstream, but I am of the opinion that we should wait until they update their pypi package with a new version number.
